import React from "react"
import styles from "./overviewWithMedia.module.scss"

export default ({ block }) => {
  return (
    <section className={styles.section}>
      <div className={styles.progressSection}>
        <div
          className={`${styles.progressSectionInner} animate__animated animate__fadeInLeft`}
        >
          <div className={styles.progressSectionLeft}>
            <h3>National Center for Wellness and Recovery</h3>
            <p>
              Addiction is a powerful disease hurting families and communities
              across America. The National Center for Wellness and Recovery
              (NCWR) is leading the charge to end the nation’s opioid crisis
              through scientific research, treatment and understanding.
            </p>
          </div>
          <div className={styles.progressSectionRight}>
            <h4>
              #1 in addiction care and research.
              <br />
              <br />
              By researching the science of pain and addiction, we can bring new
              treatments and alternatives to the forefront of care.
            </h4>
            <div className={styles.progressSectionVideos}>
              <img src="/A47E3281.jpg" />
              <div className={styles.playBtn}>
                <img src="/play.svg" />
              </div>
            </div>
            <p>
              The neurological effects <br />
              of extended opioid use
            </p>
          </div>
        </div>
        <div
          className={`${styles.progressSectionInner} animate__animated animate__fadeInRight`}
        >
          <div className={styles.progressSectionLeft}>
            <img src="/A2579DB5.jpg" />
          </div>
          <div className={styles.progressSectionRight}>
            <h4>Our research is removing stigma and creating options.</h4>
            <span>
              Through $177.5M in funding generated by the 2019 State of Oklahoma
              settlement against a major pharmaceutical opioid manufacturer, the
              National Center for Wellness and Recovery is leading the nation in
              substance use disorder research. <br />
              <br />
              With greater understanding comes greater solutions.
            </span>
            <button className={styles.btn}>
              Discover the research{" "}
              <img style={{ marginBottom: 0 }} src="/right-arrows.svg" />
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}
