import Contact from './contact/contact'
import ContactImageText from './contactImageText/contactImageText'
import DeliverHope from './deliverHope/deliverHope'
import FindTreatment from './findTreatment/findTreatment'
import Foundation from './foundation/foundation'
import Hero from './hero/hero'
import HomeResearch from './homeResearch/homeResearch'
import LatestProgress from './latestProgress/latestProgress'
import OptionChanger from './optionChanger/optionChanger'
import OsuMedicine from './osuMedicine/osuMedicine'
import OverviewWithMedia from './overviewWithMedia/overviewWithMedia'
import Research from './research/research'
import Resources from './resources/resources'
import Team from './team/team'
import Testimonial from './testimonial/testimonial'
import UnderstandingScience from './understandingScience/understandingScience'

export { Contact, ContactImageText, DeliverHope, FindTreatment, Foundation, Hero, HomeResearch, LatestProgress, OptionChanger, OsuMedicine, OverviewWithMedia, Research, Resources, Team, Testimonial, UnderstandingScience }